server:
  port: 8004
spring:
  application:
    name: provider-ticket

#eureka实例的主机名
eureka:
  instance:
    prefer-ip-address: true #使用服务的ip地址进行注册
    instance-id: provider-hystrix-8004 #自定义服务的名称信息
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/

