server:
  port: 9527
spring:
  application:
    name: zuul-gateway-9527

#eureka实例的主机名
eureka:
  instance:
    prefer-ip-address: true
    instance-id: gateway-9527.com  #使用服务的ip地址进行注册
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    myticket.serviceId: provider-ticket
    myticket.path: /myticket/**
  #禁用原地址访问
  ignored-services: provider-ticket
  #设置统一前缀
  prefix: /xixi


