server:
  port: 8762

#eureka实例的主机名
eureka:
  instance:
    hostname: eureka-server-8762
    prefer-ip-address: true

  client:
    #取消本身注册到eureka上
    register-with-eureka: false
    #不从eureka上获取服务的注册信息
    fetch-registry: false
    service-url:
     defaultZone: http://localhost:8762/eureka/