server:
  port: 8003
spring:
  application:
    name: provider-ticket

#eureka实例的主机名
eureka:
  instance:
    prefer-ip-address: true #使用服务的ip地址进行注册
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/

info:
    app.name: hello
    company.name: mycompany
    build.artifactId: $project.artifactId$
    build.version: $project.version$

