server:
  port: 8200
spring:
  application:
    name: consumer-feign-user
#eureka实例的主机名
eureka:
  instance:
    prefer-ip-address: false #使用服务的ip地址进行注册
  client:
    service-url:
     defaultZone: http://localhost:8762/eureka/, http://localhost:8761/eureka/

